name: child_moments
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  adaptive_dialog: ^1.8.0+1
  adaptive_theme: ^3.1.1
  badges: ^2.0.3
  bloc: ^8.1.0
  bottom_bar_with_sheet: ^2.4.0
  calendar_view: ^1.0.0
  chat_bubbles: ^1.3.1
  cupertino_icons: ^1.0.2
  custom_alert_dialog_box: ^1.0.2
  custom_radio_group_list: ^1.0.0
  data_grid: ^0.0.8
  data_table_2: ^2.3.7
  data_tables: ^1.4.0
  dio: ^4.0.6
  easy_table: ^2.0.1
  file_picker: ^4.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.5.4
  fluttertoast: ^8.1.1
  horizontal_data_table: ^4.1.2+2
  image_picker: ^0.8.6
  image_pickers: ^2.0.0+2
  images_picker: ^1.2.11
  intl: ^0.17.0
  new_gradient_app_bar: ^0.2.0
  no_context_navigation: ^2.1.2
  open_file: ^3.2.1
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  pluto_grid: ^5.2.0
  scalable_data_table: ^0.0.2
  shared_preferences: ^2.0.15
  syncfusion_flutter_calendar: ^20.3.49
  syncfusion_flutter_datagrid: ^20.3.50
  syncfusion_flutter_datagrid_export: ^20.3.50-beta
  syncfusion_flutter_datepicker: ^20.3.49
  syncfusion_flutter_pdf: ^20.3.50
  toggle_switch: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/logos/
    - assets/logos/logo.png
    - assets/photos/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
